import Head from 'next/head'

const GreetMain = () => {
    return (
        <>
            <Head>
                <title>Default Yo - Boomarket</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style={{"text-align":"center","paddingTop":"25%"}}>
                <h1>Yo whatsup</h1>
            </div>
        </>
    )
}

export default GreetMain;