import {useRouter} from "next/router"
import Head from 'next/head'

const Profile = () => {
    const router = useRouter();
    const {usrname} = router.query
    return (
        <>
            <Head>
                <title>{usrname} Profile - Boomarket</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>hey {usrname}</h1>
            </div>
        </>
    )
}

export default Profile;