import Head from 'next/head'

const ProfileMain = () => {
    return (
        <>
            <Head>
                <title>Default Profile - Boomarket</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Profile General</h1>
            </div>
        </>
    )
}

export default ProfileMain;