import Head from 'next/head'

const About = () => {
    return (
        <>
            <Head>
                <title>About - Boomarket</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>hits iis aboiut</h1>
            </div>
        </>
    )
}

export default About;