import Axios from "axios";
import Head from 'next/head'
import styles from "@/styles/Cryptocoins.module.css"

const CryptoArr = ({ coinData }) => {
    console.log(coinData)
    return (
        <>
            <Head>
                <title>Current Price - Boomarket</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.parent}>
                {coinData.coins.map((crypto)=>{
                    return (
                        <div className={styles.coinData} key={crypto.id}>
                            <h1>{crypto.name}</h1>
                            <div className={styles.coinDetail}>
                                <img className={styles.coinImg} src={crypto.icon}/>
                                <p className={styles.coinPrice}>{crypto.price}</p>
                            </div>
                        </div>
                    )
                })}
            </div>
        </>
    )
}

export const getStaticProps = async () => {
    const data = await Axios.get(
      "https://api.coinstats.app/public/v1/coins?skip=0"
    );
  
    return {
      props: {
        coinData: data.data,
      },
      revalidate: 10,
    };
  };

export default CryptoArr;